spring:
  datasource:
    url: jdbc:h2:mem:policydb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS public
    driver-class-name: org.h2.Driver
    username: sa
    password: sa

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.default_schema: public
      hibernate.dialect: org.hibernate.dialect.H2Dialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: public

  h2:
    console:
      enabled: true
      path: /h2-console  # optional but handy
app:
   jwt:
     # 32+ chars (256-bit) secret; for demo only. 
     # In production, we should use a secure vault or environment variable
     secret: "change-me-change-me-change-me-change-me-256-bit"
     issuer: "policy-service"
     ttl-minutes: 30
server:
  port: 8080
