spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/policydb
    username: policy
    password: policy
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.default_schema: public
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: public