-- Policies table
CREATE TABLE IF NOT EXISTS POLICIES (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  policy_number VARCHAR(16) NOT NULL UNIQUE,
  customer_id   VARCHAR(64) NOT NULL,
  coverage_amount DOUBLE PRECISION NOT NULL,
  effective_date DATE NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_policies_policy_number ON POLICIES(policy_number);
