CREATE TABLE CUSTOMERS (
  id UUID PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(150) UNIQUE NOT NULL,
    phone VARCHAR(50)
);

ALTER TABLE policy
ADD COLUMN customer_id BIGINT NOT NULL,
ADD CONSTRAINT fk_policy_customer FOREIGN KEY (customer_id) REFERENCES CUSTOMERS(id);